#!/usr/bin/env python3
"""Install / uninstall / reinstall myclaude into a Claude config dir.

Symlinks every item under ``installables/<category>/<name>`` to
``<claude-dir>/<category>/<name>`` using absolute paths, so edits in this
repo are visible to Claude immediately and vice versa.
"""

from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Tuple

REPO_ROOT = Path(__file__).resolve().parent
SOURCE_ROOT = REPO_ROOT / "installables"

# The global CLAUDE.md is special: it is NOT symlinked like everything else.
# Instead a real (machine-specific) wrapper file at <claude-dir>/CLAUDE.md
# `@`-imports the tracked source below. So we exclude this category from the
# generic symlink discovery and handle it with its own install logic.
GLOBAL_MD_CATEGORY = "global-claude-md"
GLOBAL_MD_SOURCE = SOURCE_ROOT / GLOBAL_MD_CATEGORY / "CLAUDE.md"
# Stable sentinel that identifies a wrapper as ours, independent of paths
# (paths move if the repo relocates; this marker does not).
GLOBAL_WRAPPER_MARKER = "myclaude:global-wrapper"

# settings.json is also special: a whole-file symlink (JSON has no import
# mechanism, so the wrapper trick can't apply). Install backs up any foreign
# settings.json; uninstall restores the newest backup.
SETTINGS_CATEGORY = "settings-json"
SETTINGS_SOURCE = SOURCE_ROOT / SETTINGS_CATEGORY / "settings.json"

Item = Tuple[str, str, Path]  # (category, name, absolute source path)


def discover_items() -> List[Item]:
    """Return every installable item as (category, name, absolute_source).

    Skips ``GLOBAL_MD_CATEGORY`` — the global CLAUDE.md is installed as a
    wrapper, not a symlink (see ``install_global_md``).
    """
    if not SOURCE_ROOT.is_dir():
        raise FileNotFoundError(f"{SOURCE_ROOT} not found")
    items: List[Item] = []
    for category_dir in sorted(SOURCE_ROOT.iterdir()):
        if not category_dir.is_dir():
            continue
        if category_dir.name in (GLOBAL_MD_CATEGORY, SETTINGS_CATEGORY):
            continue
        for entry in sorted(category_dir.iterdir()):
            items.append((category_dir.name, entry.name, entry.resolve()))
    return items


def target_for(claude_dir: Path, category: str, name: str) -> Path:
    return claude_dir / category / name


def is_our_symlink(target: Path, source: Path) -> bool:
    """True iff ``target`` is a symlink whose absolute target equals ``source``."""
    if not target.is_symlink():
        return False
    link = Path(os.readlink(target))
    return link == source


def describe_existing(target: Path) -> str:
    if target.is_symlink():
        return f"symlink to {os.readlink(target)}"
    if target.is_dir():
        return "existing directory"
    if target.is_file():
        return "existing file"
    return "existing entry"


def _tag(dry_run: bool) -> str:
    return "[dry-run] " if dry_run else ""


# --- global CLAUDE.md wrapper handling -------------------------------------


def is_our_global_wrapper(target: Path) -> bool:
    """True iff ``target`` is a real file containing our sentinel marker.

    A symlink is never ours (our wrapper is always a real file), so a
    pre-existing symlinked CLAUDE.md is treated as foreign.
    """
    try:
        if target.is_symlink() or not target.is_file():
            return False
        return GLOBAL_WRAPPER_MARKER in target.read_text(errors="ignore")
    except OSError:
        return False


def _wrapper_text(import_paths: List[Path]) -> str:
    lines = [
        "# WARNING: Managed by myclaude — DO NOT EDIT THIS FILE.",
        "# It is a generated wrapper. Edit the real global config here:",
        f"#   {GLOBAL_MD_SOURCE}",
        f"# {GLOBAL_WRAPPER_MARKER}:v1   (recognition marker — do not remove)",
        "",
    ]
    lines += [f"@{p}" for p in import_paths]
    lines.append("")
    return "\n".join(lines)


def _backup_path(target: Path, base: str) -> Path:
    """A non-colliding ``<base>.backup.<stamp>`` next to ``target``."""
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    parent = target.parent
    backup = parent / f"{base}.backup.{stamp}"
    i = 1
    while backup.exists() or backup.is_symlink():
        backup = parent / f"{base}.backup.{stamp}.{i}"
        i += 1
    return backup


def _newest_backup(target: Path, base: str) -> Path | None:
    """Most recent ``<base>.backup.*`` next to ``target`` (timestamp sorts)."""
    backups = sorted(target.parent.glob(f"{base}.backup.*"))
    return backups[-1] if backups else None


def install_global_md(claude_dir: Path, dry_run: bool, assume_yes: bool) -> int:
    """Install the global CLAUDE.md wrapper (the merge-capable path).

    - absent            -> write wrapper importing our source
    - already our wrapper -> NOOP (never re-backup / re-stack)
    - foreign file/link -> confirm, back it up, wrap backup + our source
    """
    tag = _tag(dry_run)
    target = claude_dir / "CLAUDE.md"
    source = GLOBAL_MD_SOURCE

    if not source.is_file():
        print(f"{tag}GLOBAL SKIP: source missing ({source})")
        return 0

    if is_our_global_wrapper(target):
        print(f"{tag}GLOBAL NOOP: {target} (already our wrapper)")
        return 0

    if not target.exists() and not target.is_symlink():
        if not dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(_wrapper_text([source]))
        print(f"{tag}GLOBAL WRAP: {target} -> imports {source}")
        return 0

    # Foreign CLAUDE.md present — the merge case.
    print(f"{tag}GLOBAL: existing {describe_existing(target)} at {target}")
    print("        This is NOT a myclaude wrapper.")
    if not assume_yes:
        if not sys.stdin.isatty():
            print(f"{tag}GLOBAL SKIP: no tty and --yes not given; left untouched.")
            return 0
        resp = input(
            "        Back it up and wrap both it + the myclaude global "
            "CLAUDE.md? [y/N] "
        ).strip().lower()
        if resp not in ("y", "yes"):
            print(f"{tag}GLOBAL SKIP: left untouched.")
            return 0

    backup = _backup_path(target, "CLAUDE.md")
    if not dry_run:
        target.rename(backup)
        target.write_text(_wrapper_text([backup, source]))
    print(f"{tag}GLOBAL BACKUP: {target} -> {backup}")
    print(f"{tag}GLOBAL WRAP: {target} -> imports {backup} + {source}")
    return 0


def reinstall_global_md(claude_dir: Path, dry_run: bool) -> int:
    """Conservative variant: create if missing, else leave untouched.

    Never backs up: our wrapper short-circuits to NOOP via the marker, and a
    foreign file is only skipped.
    """
    tag = _tag(dry_run)
    target = claude_dir / "CLAUDE.md"
    source = GLOBAL_MD_SOURCE

    if not source.is_file():
        return 0
    if is_our_global_wrapper(target):
        print(f"{tag}GLOBAL NOOP: {target} (already our wrapper)")
        return 0
    if target.exists() or target.is_symlink():
        print(
            f"{tag}GLOBAL SKIP: {target} ({describe_existing(target)}, "
            "not ours — reinstall never backs up)"
        )
        return 0
    if not dry_run:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_wrapper_text([source]))
    print(f"{tag}GLOBAL WRAP: {target} -> imports {source}")
    return 0


def uninstall_global_md(claude_dir: Path, dry_run: bool) -> int:
    """Remove our wrapper only; leave foreign files and any backups in place."""
    tag = _tag(dry_run)
    target = claude_dir / "CLAUDE.md"

    if is_our_global_wrapper(target):
        if not dry_run:
            target.unlink()
        print(f"{tag}GLOBAL UNWRAP: {target} (removed our wrapper)")
        backups = sorted(target.parent.glob("CLAUDE.md.backup.*"))
        if backups:
            print(f"{tag}GLOBAL NOTE: backup(s) left for manual restore:")
            for b in backups:
                print(f"           {b}")
        return 0
    if target.exists() or target.is_symlink():
        print(f"{tag}GLOBAL SKIP: {target} ({describe_existing(target)}, not ours)")
    else:
        print(f"{tag}GLOBAL NOOP: {target} (not present)")
    return 0


# --- settings.json handling ------------------------------------------------


def install_settings(claude_dir: Path, dry_run: bool) -> int:
    """Symlink our settings.json, backing up any foreign one first.

    - absent          -> symlink
    - already ours     -> NOOP
    - foreign          -> back up to settings.json.backup.<stamp>, then symlink
    """
    tag = _tag(dry_run)
    target = claude_dir / "settings.json"
    source = SETTINGS_SOURCE

    if not source.is_file():
        print(f"{tag}SETTINGS SKIP: source missing ({source})")
        return 0
    if is_our_symlink(target, source):
        print(f"{tag}SETTINGS NOOP: {target} (already linked)")
        return 0
    if not target.exists() and not target.is_symlink():
        if not dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            os.symlink(source, target)
        print(f"{tag}SETTINGS LINK: {target} -> {source}")
        return 0

    backup = _backup_path(target, "settings.json")
    if not dry_run:
        target.rename(backup)
        os.symlink(source, target)
    print(f"{tag}SETTINGS BACKUP: {target} -> {backup}")
    print(f"{tag}SETTINGS LINK: {target} -> {source}")
    return 0


def reinstall_settings(claude_dir: Path, dry_run: bool) -> int:
    """Create the symlink if missing; never back up a foreign settings.json."""
    tag = _tag(dry_run)
    target = claude_dir / "settings.json"
    source = SETTINGS_SOURCE

    if not source.is_file():
        return 0
    if is_our_symlink(target, source):
        print(f"{tag}SETTINGS NOOP: {target} (already linked)")
        return 0
    if target.exists() or target.is_symlink():
        print(
            f"{tag}SETTINGS SKIP: {target} ({describe_existing(target)}, "
            "not ours — reinstall never backs up)"
        )
        return 0
    if not dry_run:
        target.parent.mkdir(parents=True, exist_ok=True)
        os.symlink(source, target)
    print(f"{tag}SETTINGS LINK: {target} -> {source}")
    return 0


def uninstall_settings(claude_dir: Path, dry_run: bool) -> int:
    """Remove our symlink, then restore the newest backup if one exists."""
    tag = _tag(dry_run)
    target = claude_dir / "settings.json"
    source = SETTINGS_SOURCE

    if is_our_symlink(target, source):
        if not dry_run:
            target.unlink()
        print(f"{tag}SETTINGS UNLINK: {target}")
        backup = _newest_backup(target, "settings.json")
        if backup is not None:
            if not dry_run:
                backup.rename(target)
            print(f"{tag}SETTINGS RESTORE: {backup} -> {target}")
        else:
            print(f"{tag}SETTINGS NOTE: no backup to restore.")
        return 0
    if target.exists() or target.is_symlink():
        print(f"{tag}SETTINGS SKIP: {target} ({describe_existing(target)}, not ours)")
    else:
        print(f"{tag}SETTINGS NOOP: {target} (not present)")
    return 0


def cmd_install(
    claude_dir: Path, allow_partial: bool, dry_run: bool, assume_yes: bool
) -> int:
    items = discover_items()
    tag = _tag(dry_run)

    plan: List[Tuple[Path, Path]] = []
    noops: List[Tuple[Path, Path]] = []
    clashes: List[Tuple[Path, Path, str]] = []

    for category, name, source in items:
        target = target_for(claude_dir, category, name)
        if is_our_symlink(target, source):
            noops.append((target, source))
        elif target.is_symlink() or target.exists():
            clashes.append((target, source, describe_existing(target)))
        else:
            plan.append((target, source))

    if clashes and not allow_partial:
        print(f"{tag}ERROR: clashes detected — aborting install.")
        print("Re-run with --allow-partial-install to skip these slots.\n")
        for target, source, kind in clashes:
            print(f"  CLASH: {target}")
            print(f"         {kind}")
            print(f"         would link from: {source}")
        return 1

    if clashes:
        print(f"{tag}Skipping clashes (--allow-partial-install):")
        for target, _source, kind in clashes:
            print(f"  SKIP: {target} ({kind})")
        print()

    for target, source in noops:
        print(f"{tag}NOOP: {target} -> {source} (already linked)")

    for target, source in plan:
        if not dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            os.symlink(source, target)
        print(f"{tag}LINK: {target} -> {source}")

    print()
    install_global_md(claude_dir, dry_run, assume_yes)
    install_settings(claude_dir, dry_run)

    print(
        f"\n{tag}Done. linked={len(plan)} already_linked={len(noops)} "
        f"clashes={len(clashes)}"
    )
    return 0


def cmd_uninstall(claude_dir: Path, dry_run: bool) -> int:
    items = discover_items()
    tag = _tag(dry_run)
    removed = 0
    skipped_foreign = 0
    skipped_real = 0
    not_present = 0

    for category, name, source in items:
        target = target_for(claude_dir, category, name)
        if is_our_symlink(target, source):
            if not dry_run:
                target.unlink()
            print(f"{tag}UNLINK: {target}")
            removed += 1
            continue
        if target.is_symlink():
            print(f"{tag}SKIP: {target} (foreign symlink -> {os.readlink(target)})")
            skipped_foreign += 1
            continue
        if target.exists():
            print(f"{tag}SKIP: {target} ({describe_existing(target)}, not ours)")
            skipped_real += 1
            continue
        print(f"{tag}NOOP: {target} (not present)")
        not_present += 1

    print()
    uninstall_global_md(claude_dir, dry_run)
    uninstall_settings(claude_dir, dry_run)

    print(
        f"\n{tag}Done. removed={removed} not_present={not_present} "
        f"skipped_foreign_symlink={skipped_foreign} skipped_real={skipped_real}"
    )
    return 0


def cmd_reinstall(claude_dir: Path, dry_run: bool) -> int:
    items = discover_items()
    tag = _tag(dry_run)
    created = 0
    already = 0
    skipped = 0

    for category, name, source in items:
        target = target_for(claude_dir, category, name)
        if is_our_symlink(target, source):
            print(f"{tag}NOOP: {target} -> {source} (already linked)")
            already += 1
            continue
        if target.is_symlink() or target.exists():
            print(f"{tag}SKIP: {target} ({describe_existing(target)})")
            skipped += 1
            continue
        if not dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            os.symlink(source, target)
        print(f"{tag}LINK: {target} -> {source}")
        created += 1

    print()
    reinstall_global_md(claude_dir, dry_run)
    reinstall_settings(claude_dir, dry_run)

    print(
        f"\n{tag}Done. created={created} already_linked={already} skipped={skipped}"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Install / uninstall / reinstall myclaude into a Claude config dir.",
    )
    parser.add_argument(
        "--claude-dir",
        default=str(Path.home() / ".claude"),
        help="Target Claude config dir (default: ~/.claude).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would happen without touching the filesystem.",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_install = sub.add_parser("install", help="Create symlinks for all items.")
    p_install.add_argument(
        "--allow-partial-install",
        action="store_true",
        help="Skip clashing slots instead of aborting.",
    )
    p_install.add_argument(
        "--yes",
        action="store_true",
        help="Auto-confirm backing up a foreign global CLAUDE.md (non-interactive).",
    )

    sub.add_parser("uninstall", help="Remove symlinks that point back to this repo.")
    sub.add_parser(
        "reinstall",
        help="Create any missing symlinks; leave existing ones untouched.",
    )

    args = parser.parse_args()
    claude_dir = Path(args.claude_dir).expanduser().resolve()

    if args.cmd == "install":
        return cmd_install(
            claude_dir, args.allow_partial_install, args.dry_run, args.yes
        )
    if args.cmd == "uninstall":
        return cmd_uninstall(claude_dir, args.dry_run)
    if args.cmd == "reinstall":
        return cmd_reinstall(claude_dir, args.dry_run)
    parser.error(f"unknown command: {args.cmd}")
    return 2


if __name__ == "__main__":
    sys.exit(main())
